// Cynhyrchuwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import { conversation, conversationData, tokenStats } from "./models";

export function ClearConversation(): Promise<void>;
export function ChooseDirectory(): Promise<string>;
export function DeleteConversation(arg1: string): Promise<void>;
export function ExportConversation(arg1: string, arg2: string): Promise<void>;
export function GenerateConversationTitle(arg1: string): Promise<void>;
export function GetConversationData(): Promise<conversationData>;
export function GetConversations(): Promise<Array<conversation>>;
export function GetSettings(): Promise<Record<string, any>>;
export function GetTokenStats(): Promise<tokenStats>;
export function GetWorkDir(): Promise<string>;
export function InterruptInference(): Promise<void>;
export function NewConversation(): Promise<void>;
export function RegenerateConversationTitle(arg1: string): Promise<void>;
export function SaveSettings(arg1: Record<string, any>): Promise<void>;
export function SendMessage(arg1: string): Promise<void>;
export function SetWorkDir(arg1: string): Promise<void>;
export function SwitchConversation(arg1: string): Promise<void>;
export function UpdateConversationTitle(arg1: string, arg2: string): Promise<void>;
