// @ts-check
// Cynhyrchuwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearConversation() {
  return window['go']['gui']['App']['ClearConversation']();
}

export function ChooseDirectory() {
  return window['go']['gui']['App']['ChooseDirectory']();
}

export function DeleteConversation(arg1) {
  return window['go']['gui']['App']['DeleteConversation'](arg1);
}

export function ExportConversation(arg1, arg2) {
  return window['go']['gui']['App']['ExportConversation'](arg1, arg2);
}

export function GenerateConversationTitle(arg1) {
  return window['go']['gui']['App']['GenerateConversationTitle'](arg1);
}

export function GetConversationData() {
  return window['go']['gui']['App']['GetConversationData']();
}

export function GetConversations() {
  return window['go']['gui']['App']['GetConversations']();
}

export function GetSettings() {
  return window['go']['gui']['App']['GetSettings']();
}

export function GetTokenStats() {
  return window['go']['gui']['App']['GetTokenStats']();
}

export function GetWorkDir() {
  return window['go']['gui']['App']['GetWorkDir']();
}

export function InterruptInference() {
  return window['go']['gui']['App']['InterruptInference']();
}

export function NewConversation() {
  return window['go']['gui']['App']['NewConversation']();
}

export function RegenerateConversationTitle(arg1) {
  return window['go']['gui']['App']['RegenerateConversationTitle'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['gui']['App']['SaveSettings'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['gui']['App']['SendMessage'](arg1);
}

export function SetWorkDir(arg1) {
  return window['go']['gui']['App']['SetWorkDir'](arg1);
}

export function SwitchConversation(arg1) {
  return window['go']['gui']['App']['SwitchConversation'](arg1);
}

export function UpdateConversationTitle(arg1, arg2) {
  return window['go']['gui']['App']['UpdateConversationTitle'](arg1, arg2);
}
