// @ts-check
// Cynhyrchuwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearConversation() {
  return window['go']['gui']['App']['ClearConversation']();
}

export function GetConversationData() {
  return window['go']['gui']['App']['GetConversationData']();
}

export function GetConversations() {
  return window['go']['gui']['App']['GetConversations']();
}

export function GetTokenStats() {
  return window['go']['gui']['App']['GetTokenStats']();
}

export function GetWorkDir() {
  return window['go']['gui']['App']['GetWorkDir']();
}

export function InterruptInference() {
  return window['go']['gui']['App']['InterruptInference']();
}

export function SendMessage(arg1) {
  return window['go']['gui']['App']['SendMessage'](arg1);
}

export function SetWorkDir(arg1) {
  return window['go']['gui']['App']['SetWorkDir'](arg1);
}

export function SwitchConversation(arg1) {
  return window['go']['gui']['App']['SwitchConversation'](arg1);
}
