// Cynhyrchuwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export class conversation {
  id: string;
  title: string;
  createdAt: string;
  status: string;
  tokenUsage: number;
  messageCount: number;

  static createFrom(source: any = {}) {
    return new conversation(source);
  }

  constructor(source: any = {}) {
    if ('string' === typeof source) source = JSON.parse(source);
    this.id = source["id"];
    this.title = source["title"];
    this.createdAt = source["createdAt"];
    this.status = source["status"];
    this.tokenUsage = source["tokenUsage"];
    this.messageCount = source["messageCount"];
  }
}

export class conversationData {
  id: string;
  messages: message[];
  isStreaming: boolean;

  static createFrom(source: any = {}) {
    return new conversationData(source);
  }

  constructor(source: any = {}) {
    if ('string' === typeof source) source = JSON.parse(source);
    this.id = source["id"];
    this.messages = this.convertValues(source["messages"], message);
    this.isStreaming = source["isStreaming"];
  }

  convertValues(a: any, classs: any, asMap: boolean = false): any {
    if (!a) {
      return a;
    }
    if (a.slice && a.map) {
      return (a as any[]).map((elem) => this.convertValues(elem, classs));
    } else if ("object" === typeof a) {
      if (asMap) {
        for (const key of Object.keys(a)) {
          a[key] = new classs(a[key]);
        }
        return a;
      }
      return new classs(a);
    }
    return a;
  }
}

export class message {
  role: string;
  content: string;
  thinking: string;
  toolCalls: toolCall[];
  tokenUsage: number;
  isStreaming: boolean;
  streamingType: string;
  timestamp: string;

  static createFrom(source: any = {}) {
    return new message(source);
  }

  constructor(source: any = {}) {
    if ('string' === typeof source) source = JSON.parse(source);
    this.role = source["role"];
    this.content = source["content"];
    this.thinking = source["thinking"];
    this.toolCalls = this.convertValues(source["toolCalls"], toolCall);
    this.tokenUsage = source["tokenUsage"];
    this.isStreaming = source["isStreaming"];
    this.streamingType = source["streamingType"];
    this.timestamp = source["timestamp"];
  }

  convertValues(a: any, classs: any, asMap: boolean = false): any {
    if (!a) {
      return a;
    }
    if (a.slice && a.map) {
      return (a as any[]).map((elem) => this.convertValues(elem, classs));
    } else if ("object" === typeof a) {
      if (asMap) {
        for (const key of Object.keys(a)) {
          a[key] = new classs(a[key]);
        }
        return a;
      }
      return new classs(a);
    }
    return a;
  }
}

export class toolCall {
  id: string;
  name: string;
  arguments: string;
  isComplete: boolean;
  result: string;
  resultError: string;

  static createFrom(source: any = {}) {
    return new toolCall(source);
  }

  constructor(source: any = {}) {
    if ('string' === typeof source) source = JSON.parse(source);
    this.id = source["id"];
    this.name = source["name"];
    this.arguments = source["arguments"];
    this.isComplete = source["isComplete"];
    this.result = source["result"];
    this.resultError = source["resultError"];
  }
}

export class tokenStats {
  totalTokens: number;
  inferenceCount: number;

  static createFrom(source: any = {}) {
    return new tokenStats(source);
  }

  constructor(source: any = {}) {
    if ('string' === typeof source) source = JSON.parse(source);
    this.totalTokens = source["totalTokens"];
    this.inferenceCount = source["inferenceCount"];
  }
}
