# PyInstaller 配置文件
# 用于将 mem0 server 打包为独立的可执行文件

a = Analysis(
    ['run_server.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('main.py', '.'),
    ],
    hiddenimports=[
        'fastapi',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.websockets',
        'pydantic',
        'pydantic.fields',
        'pydantic_core',
        'mem0',
        'mem0.memory',
        'mem0.memory.main',
        'mem0.vector_stores',
        'mem0.vector_stores.faiss',
        'mem0.llms',
        'mem0.llms.lmstudio',
        'mem0.embeddings',
        'mem0.embeddings.lmstudio',
        'mem0.utils',
        'mem0.utils.factory',
        'faiss',
        'numpy',
        'openai',
        'httpx',
        'httpx._transports.default',
        'httpcore',
        'httpcore._backends.anyio',
        'anyio',
        'anyio._backends._asyncio',
        'sniffio',
        'jinja2',
        'starlette',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        'h11',
        'click',
        'dotenv',
        'python_dotenv',
        'colorama',
        'logging',
        'asyncio',
        'concurrent.futures',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='mem0-server',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # 使用控制台以便查看日志
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
